

services:
    # -----------------------------
    # Keycloak Identity Server
    # -----------------------------
    keycloak:
        image: quay.io/keycloak/keycloak:24.0.1
        container_name: keycloak
        command: start-dev
        ports:
            - "8181:8080"  # Keycloak UI
        environment:
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin
        volumes:
            - keycloak_data:/opt/keycloak/data
        networks:
            - ecommerce-net

    # -----------------------------
    # Eureka Service Registry
    # -----------------------------
    eureka-server:
        build:
            context: ./eureka-server
        container_name: eureka-server
        ports:
            - "8761:8761"
        networks:
            - ecommerce-net

    # -----------------------------
    # MySQL for Cart Service
    # -----------------------------
    mysql:
        image: mysql:8.3
        container_name: mysql-cart-service
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: cartdb
        ports:
            - "3307:3306"

        volumes:
            - mysql_cart_data:/var/lib/mysql
        networks:
            - ecommerce-net

    # -----------------------------
    # Redis for Cart Service
    # -----------------------------
    redis:
        image: redis:7
        container_name: redis-cart
        restart: always
        ports:
            - "6379:6379"
        networks:
            - ecommerce-net

    # -----------------------------
    # MongoDB for Product Service
    # -----------------------------
    mongodb:
        image: mongo:6.0
        container_name: mongodb-product-service
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
        ports:
            - "27017:27017"
        networks:
            - ecommerce-net

    # -----------------------------
    # MySQL for Order Service
    # -----------------------------
    mysql-order:
        image: mysql:8.3
        container_name: mysql-order-service
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: order-service
        ports:
            - "3308:3306"
        volumes:
            - mysql_order_data:/var/lib/mysql
        networks:
            - ecommerce-net

    # -----------------------------
    # MySQL for Inventory Service
    # -----------------------------
    mysql-inventory:
        image: mysql:8.3
        container_name: mysql-inventory-service
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: inventory_service
        ports:
            - "3309:3306"
        volumes:
            - mysql_inventory_data:/var/lib/mysql
        networks:
            - ecommerce-net

    # -----------------------------
    # MySQL for User Service
    # -----------------------------
    mysql-user:
        image: mysql:8.3
        container_name: mysql-user-service
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: userdb
        ports:
            - "3310:3306"
        volumes:
            - mysql_user_data:/var/lib/mysql
        networks:
            - ecommerce-net

    # -----------------------------
    # MySQL for Admin Service
    # -----------------------------
    mysql-admin-service:
        image: mysql:8.3
        container_name: mysql-admin-service
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: admin_db
        ports:
            - "3311:3306"
        volumes:
            - mysql_admin_data:/var/lib/mysql
        networks:
            - ecommerce-net

    # -----------------------------
    # Product Service
    # -----------------------------
    product-service:
        build:
            context: ./product-service
        container_name: product-service
        ports:
            - "8081:8081"
        depends_on:
            - mongodb
            - eureka-server
        environment:
            SPRING_PROFILES_ACTIVE: docker
            SPRING_DATA_MONGODB_URI: mongodb://root:password@mongodb:27017/product-service?authSource=admin
            EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
        networks:
            - ecommerce-net

    # -----------------------------
    # Cart Service
    # -----------------------------
    cart-service:
        build:
            context: ./cart-service
        container_name: cart-service
        ports:
            - "8082:8082"
        depends_on:
            - mysql
            - redis
            - eureka-server
        environment:
            SPRING_PROFILES_ACTIVE: docker
            SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/cartdb
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_PASSWORD: root
            SPRING_REDIS_HOST: redis-cart
            SPRING_REDIS_PORT: 6379
            EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
        networks:
            - ecommerce-net

    # -----------------------------
    # Order Service
    # -----------------------------
    order-service:
        build:
            context: ./order-service
        container_name: order-service
        ports:
            - "8083:8083"
        depends_on:
            - mysql-order
            - eureka-server
        environment:
            SPRING_PROFILES_ACTIVE: docker
            SPRING_DATASOURCE_URL: jdbc:mysql://mysql-order:3306/order-service
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_PASSWORD: root
            EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
        networks:
            - ecommerce-net

    # -----------------------------
    # Inventory Service
    # -----------------------------
    inventory-service:
        build:
            context: ./inventory-service
        container_name: inventory-service
        ports:
            - "8086:8086"
        depends_on:
            - mysql-inventory
            - eureka-server
        environment:
            SPRING_PROFILES_ACTIVE: docker
            SPRING_DATASOURCE_URL: jdbc:mysql://mysql-inventory:3306/inventory_service
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_PASSWORD: root
            EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
        networks:
            - ecommerce-net

    # -----------------------------
    # User Service
    # -----------------------------
    user-service:
        build:
            context: ./user-service
        container_name: user-service
        ports:
            - "8087:8087"
        depends_on:
            - mysql-user
            - eureka-server
        environment:
            SPRING_PROFILES_ACTIVE: docker
            SPRING_DATASOURCE_URL: jdbc:mysql://mysql-user:3306/userdb
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_PASSWORD: root
            EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
        networks:
            - ecommerce-net

    # -----------------------------
    # Admin Service
    # -----------------------------
    admin-service:
        build:
            context: ./admin-service
        container_name: admin-service
        ports:
            - "8088:8088"
        depends_on:
            - mysql-admin-service
            - eureka-server
        environment:
            SPRING_PROFILES_ACTIVE: docker
            SPRING_DATASOURCE_URL: jdbc:mysql://mysql-admin-service:3306/admin_db
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_PASSWORD: root
            EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
        networks:
            - ecommerce-net

    # -----------------------------
    # API Gateway
    # -----------------------------
    gateway-service:
        build:
            context: ./gateway
        container_name: gateway-service
        ports:
            - "8084:8084"
        depends_on:
            - eureka-server
            - keycloak
        environment:
            SPRING_PROFILES_ACTIVE: docker
            SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/realms/spring-microservices-realm
            EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
        networks:
            - ecommerce-net

# -----------------------------
# Named Volumes
# -----------------------------
volumes:
    mysql_cart_data:
    mysql_order_data:
    mysql_inventory_data:
    mysql_user_data:
    mysql_admin_data:
    keycloak_data:

# -----------------------------
# Docker Network
# -----------------------------
networks:
    ecommerce-net:
        driver: bridge
