# -------- Stage 1: Build the application --------
FROM maven:3.9.6-eclipse-temurin-21 AS build

WORKDIR /app

# Copy pom.xml and download dependencies
COPY pom.xml .
RUN mvn dependency:go-offline -B

# Copy source code
COPY src ./src

# Build the project
RUN mvn clean package -DskipTests

# -------- Stage 2: Run the application --------
FROM eclipse-temurin:21-jdk-alpine

WORKDIR /app

# Copy the jar from the previous stage
COPY --from=build /app/target/cart-service-0.0.1-SNAPSHOT.jar app.jar

# Expose the app port (change if needed)
EXPOSE 8083

# Run the app
ENTRYPOINT ["java", "-jar", "app.jar"]
