# ------------------------------
# Application
spring.application.name=user-service
server.port=8089

# ------------------------------
# Database (Local IntelliJ + Docker DB)
spring.datasource.url=jdbc:mysql://localhost:3310/userdb
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# ------------------------------
# Flyway
spring.flyway.enabled=false

# ------------------------------
# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

# ------------------------------
# Eureka (Docker host)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# ------------------------------
# Keycloak (Docker host)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8181/realms/spring-microservices-realm
spring.security.oauth2.client.registration.keycloak.client-id=user-service
spring.security.oauth2.client.registration.keycloak.client-secret=TFzEDs9Y6hmJuH9UzNrJ0Zm9bfL70rW5
spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8181/realms/spring-microservices-realm

# ------------------------------
# Resilience4j
resilience4j.circuitbreaker.instances.user-service.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.user-service.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.user-service.slidingWindowSize=5
resilience4j.circuitbreaker.instances.user-service.failureRateThreshold=50
resilience4j.circuitbreaker.instances.user-service.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.user-service.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.user-service.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.circuitbreaker.instances.user-service.minimum-number-of-calls=5
resilience4j.timelimiter.instances.user-service.timeout-duration=3s
resilience4j.retry.instances.user-service.max-attempts=3
resilience4j.retry.instances.user-service.wait-duration=2s

# ------------------------------
# Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
