spring.application.name=order-service
server.port=8088

# Flyway
spring.flyway.enabled=true

# DB (using Docker-exposed port)
spring.datasource.url=jdbc:mysql://localhost:3308/order-service
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=none

# Inter-service communication (local port mapping of inventory-service)
inventory.url=http://localhost:8086

# Kafka (running locally or exposed via Docker)
spring.kafka.bootstrap-servers=localhost:9092

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Keycloak (same as docker for token compatibility)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8181/realms/spring-microservices-realm
spring.security.oauth2.client.registration.keycloak.client-id=inventory-service
spring.security.oauth2.client.registration.keycloak.client-secret=HnwhNEDM7bEnUTgM1SYa1MLv0fhzdlq1
spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8181/realms/spring-microservices-realm

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

# Resilience4j
resilience4j.circuitbreaker.instances.order-service.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.order-service.event-consumer-buffer-size=10
resilience4j.circuitbreaker.instances.order-service.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.order-service.slidingWindowSize=5
resilience4j.circuitbreaker.instances.order-service.failureRateThreshold=50
resilience4j.circuitbreaker.instances.order-service.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.order-service.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.order-service.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.circuitbreaker.instances.order-service.minimum-number-of-calls=5

resilience4j.timelimiter.instances.order-service.timeout-duration=3s
resilience4j.retry.instances.order-service.max-attempts=3
resilience4j.retry.instances.order-service.wait-duration=5s
