spring.application.name=ecommapp
#spring.data.mongodb.uri= mongodb://localhost:27017/product-service
spring.data.mongodb.uri= mongodb://root:password@localhost:27017/product-service?authSource=admin
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

#Resilinece4j Properties
resilience4j.circuitbreaker.instances.product-servie.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.product-servie.event-consumer-buffer-size=10
resilience4j.circuitbreaker.instances.product-servie.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.product-servie.slidingWindowSize=5
resilience4j.circuitbreaker.instances.product-servie.failureRateThreshold=50
resilience4j.circuitbreaker.instances.product-servie.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.product-servie.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.product-servie.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.circuitbreaker.instances.product-servie.minimum-number-of-calls=5

#Resilience4J Timeout Properties
resilience4j.timelimiter.instances.product-servie.timeout-duration=3s

#Resilience4J Retry Properties
resilience4j.retry.instances.product-servie.max-attempts=3
resilience4j.retry.instances.product-servie.wait-duration=5s