# ======================
# = Service Info =
# ======================
spring.application.name=product-service
server.port=8081

# ======================
# = MongoDB Configuration =
# ======================
spring.data.mongodb.uri=mongodb://root:password@mongodb:27017/product-service?authSource=admin

# ======================
# = Eureka Discovery =
# ======================
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true

# ======================
# = Keycloak Security =
# ======================
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8181/realms/spring-microservices-realm
spring.security.oauth2.client.registration.keycloak.client-id=product-service
spring.security.oauth2.client.registration.keycloak.client-secret=mIFnXG49oEtk6L9DchWq1C3yRjDRuzVn
spring.security.oauth2.client.provider.keycloak.issuer-uri=http://keycloak:8080/realms/spring-microservices-realm


# ======================
# = OpenAPI Swagger Docs =
# ======================
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

# ======================
# = Resilience4j Config =
# ======================
resilience4j.circuitbreaker.instances.product-service.register-health-indicator=true
resilience4j.circuitbreaker.instances.product-service.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.product-service.sliding-window-size=5
resilience4j.circuitbreaker.instances.product-service.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.product-service.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.product-service.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.product-service.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.product-service.wait-duration-in-open-state=5s

resilience4j.timelimiter.instances.product-service.timeout-duration=3s
resilience4j.retry.instances.product-service.max-attempts=3
resilience4j.retry.instances.product-service.wait-duration=5s

# ======================
# = Actuator (optional) =
# ======================
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
